# Generated by Django 4.2.1 on 2023-05-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='chemin vers fichier')),
                ('video', models.FileField(upload_to='chemin')),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('update_at', models.DateTimeField(verbose_name='date update')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('comments', models.ManyToManyField(to='firstApp.comment')),
            ],
        ),
    ]
